version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy    
    container_name: app  
    restart: unless-stopped
    volumes:    
      - .:/workspace:cached    
    command: sleep infinity
    networks:
      - servicenet
    links:
      - "db:database"

  db:
    image: mysql:latest
    container_name: db    
    ports:
      - "13306:3306"
    restart: unless-stopped
    volumes:
      - app_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: vscode
      MYSQL_USER: vscode
      MYSQL_PASSWORD: vscode
    networks:
      - servicenet
volumes:
    app_data:

networks:
  servicenet: